  """add_room_to_resource_type

Revision ID: 2b3877664e70
Revises: f73f287705ff
Create Date: 2026-01-01 15:24:54.421174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3877664e70'
down_revision: Union[str, Sequence[str], None] = 'f73f287705ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE resourcetype ADD VALUE 'ROOM'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
