"""create_profiles_table_and_trigger

Revision ID: e253bcda3613
Revises: 307ceb054af9
Create Date: 2026-01-05 09:17:01.921726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e253bcda3613'
down_revision: Union[str, Sequence[str], None] = '307ceb054af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'email',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('profiles', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('profiles', 'role',
               existing_type=postgresql.ENUM('manager', 'receptionist', 'technician', 'customer', name='user_role'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::user_role"))
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # PROTECT FK to auth.users: Do not drop it even if model doesn't specify it explicitly yet.
    # op.drop_constraint(op.f('profiles_id_fkey'), 'profiles', type_='foreignkey')

    op.alter_column('staff_profiles', 'bio',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('staff_profiles_user_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'staff_profiles', 'profiles', ['user_id'], ['id'])
    op.drop_column('staff_profiles', 'is_active')
    op.drop_index(op.f('ix_staff_schedules_staff_id'), table_name='staff_schedules')
    op.drop_index(op.f('ix_staff_schedules_work_date'), table_name='staff_schedules')

    # === CUSTOM TRIGGER FOR SUPABASE AUTH ===
    op.execute("""
    CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS trigger AS $$
    BEGIN
      INSERT INTO public.profiles (id, email, full_name, role, is_active)
      VALUES (
        new.id,
        new.email,
        new.raw_user_meta_data->>'full_name',
        COALESCE(new.raw_user_meta_data->>'role', 'customer'),
        true
      )
      ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name),
        role = COALESCE(EXCLUDED.role, public.profiles.role);
      RETURN new;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;
    """)

    op.execute("""
    DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
    """)

    op.execute("""
    CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_staff_schedules_work_date'), 'staff_schedules', ['work_date'], unique=False)
    op.create_index(op.f('ix_staff_schedules_staff_id'), 'staff_schedules', ['staff_id'], unique=False)
    op.add_column('staff_profiles', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('staff_profiles_user_id_fkey'), 'staff_profiles', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('staff_profiles', 'bio',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('profiles_id_fkey'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_unique_constraint(op.f('profiles_email_key'), 'profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('profiles', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('manager', 'receptionist', 'technician', 'customer', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::user_role"))
    op.alter_column('profiles', 'avatar_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'phone_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # === CUSTOM TRIGGER DOWNGRADE ===
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;")
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_user();")
    # ### end Alembic commands ###
