"""add_auditing_and_sync_timezones

Revision ID: f73f287705ff
Revises: a9f73cba70a6
Create Date: 2025-12-31 19:15:53.796261

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f73f287705ff'
down_revision: Union[str, Sequence[str], None] = 'a9f73cba70a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Thêm cột nullable trước
    op.add_column('resources', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('resources', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('service_categories', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('service_categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skills', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # 2. Điền giá trị hiện tại (now) cho các bản ghi cũ
    # Lưu ý: Dùng SQL trực tiếp cho đơn giản và hiệu quả
    op.execute("UPDATE resources SET created_at = now(), updated_at = now()")
    op.execute("UPDATE service_categories SET created_at = now(), updated_at = now()")
    op.execute("UPDATE skills SET created_at = now(), updated_at = now()")

    # 3. Chuyển sang NOT NULL sau khi đã điền dữ liệu
    op.alter_column('resources', 'created_at', nullable=False)
    op.alter_column('resources', 'updated_at', nullable=False)
    op.alter_column('service_categories', 'created_at', nullable=False)
    op.alter_column('service_categories', 'updated_at', nullable=False)
    op.alter_column('skills', 'created_at', nullable=False)
    op.alter_column('skills', 'updated_at', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    op.drop_column('service_categories', 'updated_at')
    op.drop_column('service_categories', 'created_at')
    op.drop_column('resources', 'updated_at')
    op.drop_column('resources', 'created_at')
    # ### end Alembic commands ###
